// ignore_for_file: unnecessary_string_escapes, equal_keys_in_map

import 'package:get/get.dart';

final class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          //NEW
          "Good to see you again": "Good to see you again",
          'Shop Smart, Celebrate Big!': 'Shop Smart, Celebrate Big!',
          'Seamlessly plan your event and transform every moment into a lasting memory!':
              'Seamlessly plan your event and transform every moment into a lasting memory!',
          'Choose Your Language': 'Choose Your Language',
          'Get Started': 'Get Started',
          'Sign up': 'Sign up',
          'Welcome!': 'Welcome!',
          'Sign up to Continue': 'Sign up to Continue',
          'Your Name': 'Your Name',
          'Enter your name': 'Enter your name',
          'Shop Name': 'Shop Name',
          'Enter your shop name': 'Enter your shop name',
          'Phone Number': 'Phone Number',
          'Enter your number': 'Enter your number',
          'Continue': 'Continue',
          'Already have an account? ': 'Already have an account? ',
          'Login': 'Login',
          'Verification Code': 'Verification Code',
          'We will send verification code on your phone number':
              'We will send verification code on your phone number',
          'Code': 'Code',
          '4-Type of Number': '4-Type of Number',
          'Verify': 'Verify',
          'Log in': 'Log in',
          'Welcome back!': 'Welcome back!',
          'Stay signed in with your account to make easier':
              'Stay signed in with your account to make easier',
          'Mobile Number': 'Mobile Number',
          'Enter your mobile number': 'Enter your mobile number',
          'Log in': 'Log in',
          'Setting': 'Setting',
          'Log Out': 'Log Out',
          'Are You Sure you Want to log out':
              'Are You Sure you Want to log out',
          'Cancel': 'Cancel',
          'Yes, Log Out': 'Yes, Log Out',
          'Search product': 'Search product',
          'Back': 'Back',
          'Call an Advisor': 'Call an Advisor',
          'Chat on WhatsApp': 'Chat on WhatsApp',
          'All Categories': 'All Categories',
          'Most Sales': 'Most Sales',
          'Our Offer': 'Our Offer',
          'All Products': 'All Products',
          'My Cart': 'My Cart',
          'Remove': 'Remove',
          'Subtotal:': 'Subtotal:',
          'Logistics cost:': 'Logistics cost:',
          'Logistics discount:': 'Logistics discount:',
          'VAT:': 'VAT:',
          'Total Amount:': 'Total Amount:',
          'Order Now': 'Order Now',
          'Enter your address': 'Enter your address',
          'Add Address': 'Add Address',
          'Venice': 'Venice',
          'Continue': 'Continue',
          'Thank You!': 'Thank You!',
          'Your order has been successfully placed.':
              'Your order has been successfully placed.',
          'View Details': 'View Details',
          'Deliver to ': 'Deliver to ',
          'Total Payable Amount': 'Total Payable Amount',
          'Explore more products': 'Explore more products',
          'Checkout': 'Checkout',
          'Name': 'Name',
          'Phone': 'Phone',
          'Shop Name': 'Shop Name',
          'Location': 'Location',
          'Edit Profile': 'Edit Profile',
          'Save': 'Save',
          'Add to Cart': 'Add to Cart',
          'Rate': 'Rate',
          'Ratings & Reviews': 'Ratings & Reviews',
          'Product Details': 'Product Details',
          'Home': 'Home',
          'Category': 'Category',
          'Order': 'Order',
          'Profile': 'Profile',
          'Tracking Order': 'Tracking Order',
          'Complete Order': 'Complete Order',
          'Arabic': 'Arabic',
          'French': 'French',
          'Notification': 'Notification',
          'Add Cart': 'Add Cart',
          'Product Request': 'Product Request',
          'Thank You For Using Review!': 'Thank You For Using Review!',
          'Give a Review': 'Give a Review',
          'Review Heading': 'Review Heading',
          'Text': 'Text',
          'Detail Review': 'Detail Review',
          'Details': 'Details',
          'Submit': 'Submit',
          'Verify account': 'Verify account',
          'Code has been send to ': 'Code has been send to ',
          ' Enter the code to verify your account.':
              ' Enter the code to verify your account.',
          'Code': 'Code',
          'Verify Account': 'Verify Account',
          'Rated': 'Rated',
          'Remove from Cart': 'Remove from Cart'
        },

        'fr_FR': {
          // NEW
          "Good to see you again": "Heureux de vous revoir",
          'Shop Smart, Celebrate Big!': 'Achetez malin, célébrez en grand !',
          'Seamlessly plan your event and transform every moment into a lasting memory!':
              'Planifiez votre événement sans effort et transformez chaque moment en souvenir inoubliable !',
          'Choose Your Language': 'Choisissez votre langue',
          'Get Started': 'Commencer',
          'Sign up': 'S’inscrire',
          'Welcome!': 'Bienvenue !',
          'Sign up to Continue': 'Inscrivez-vous pour continuer',
          'Your Name': 'Votre nom',
          'Enter your name': 'Entrez votre nom',
          'Shop Name': 'Nom de la boutique',
          'Enter your shop name': 'Entrez le nom de votre boutique',
          'Phone Number': 'Numéro de téléphone',
          'Enter your number': 'Entrez votre numéro',
          'Continue': 'Continuer',
          'Already have an account? ': 'Vous avez déjà un compte ? ',
          'Login': 'Se connecter',
          'Verification Code': 'Code de vérification',
          'We will send verification code on your phone number':
              'Nous enverrons un code de vérification sur votre numéro de téléphone',
          'Code': 'Code',
          '4-Type of Number': '4-chiffres du code',
          'Verify': 'Vérifier',
          'Log in': 'Connexion',
          'Welcome back!': 'Content de vous revoir !',
          'Stay signed in with your account to make easier':
              'Restez connecté à votre compte pour faciliter l’accès',
          'Mobile Number': 'Numéro de mobile',
          'Enter your mobile number': 'Entrez votre numéro de mobile',
          'Setting': 'Paramètres',
          'Log Out': 'Se déconnecter',
          'Are You Sure you Want to log out':
              'Êtes-vous sûr de vouloir vous déconnecter ?',
          'Cancel': 'Annuler',
          'Yes, Log Out': 'Oui, déconnexion',
          'Search product': 'Rechercher un produit',
          'Back': 'Retour',
          'Call an Advisor': 'Appeler un conseiller',
          'Chat on WhatsApp': 'Discuter sur WhatsApp',
          'All Categories': 'Toutes les catégories',
          'Most Sales': 'Meilleures ventes',
          'Our Offer': 'Notre offre',
          'All Products': 'Tous les produits',
          'My Cart': 'Mon panier',
          'Remove': 'Supprimer',
          'Subtotal:': 'Sous-total :',
          'Logistics cost:': 'Frais logistiques :',
          'Logistics discount:': 'Remise logistique :',
          'VAT:': 'TVA :',
          'Total Amount:': 'Montant total :',
          'Order Now': 'Commander maintenant',
          'Enter your address': 'Entrez votre adresse',
          'Add Address': 'Ajouter une adresse',
          'Venice': 'Venise',
          'Thank You!': 'Merci !',
          'Your order has been successfully placed.':
              'Votre commande a été passée avec succès.',
          'View Details': 'Voir les détails',
          'Deliver to ': 'Livrer à ',
          'Total Payable Amount': 'Montant total à payer',
          'Explore more products': 'Explorer plus de produits',
          'Checkout': 'Paiement',
          'Name': 'Nom',
          'Phone': 'Téléphone',
          'Location': 'Emplacement',
          'Edit Profile': 'Modifier le profil',
          'Save': 'Enregistrer',
          'Add to Cart': 'Ajouter au panier',
          'Rate': 'Évaluer',
          'Ratings & Reviews': 'Avis et évaluations',
          'Product Details': 'Détails du produit',
          'Home': 'Accueil',
          'Category': 'Catégorie',
          'Order': 'Commande',
          'Profile': 'Profil',
          'Tracking Order': 'Suivi de commande',
          'Complete Order': 'Finaliser la commande',
          'Arabic': 'Arabe',
          'French': 'Français',
          'Notification': 'Notification',
          'Add Cart': 'Ajouter au panier',
          'Product Request': 'Demande de produit',
          'Thank You For Using Review!': 'Merci d\'utiliser Review !',
          'Give a Review': 'Donner un avis',
          'Review Heading': 'Titre de l\'avis',
          'Text': 'Texte',
          'Detail Review': 'Avis détaillé',
          'Details': 'Détails',
          'Submit': 'Soumettre',
          'Verify account': 'Vérifier le compte',
          'Code has been send to ': 'Le code a été envoyé à ',
          ' Enter the code to verify your account.':
              ' Entrez le code pour vérifier votre compte.',
          'Code': 'Code',
          'Verify Account': 'Vérifier le compte',
          'Rated': 'Noté',
          'Remove from Cart': 'Retirer du panier'
        },

        'ar_AR': {
          // NEW
          "Good to see you again": "سعداء برؤيتك مرة أخرى",
          'Shop Smart, Celebrate Big!': 'تسوّق بذكاء واحتفل بشكل كبير!',
          'Seamlessly plan your event and transform every moment into a lasting memory!':
              'خطط لفعاليتك بسلاسة وحوّل كل لحظة إلى ذكرى لا تُنسى!',
          'Choose Your Language': 'اختر لغتك',
          'Get Started': 'ابدأ الآن',
          'Sign up': 'إنشاء حساب',
          'Welcome!': 'مرحباً!',
          'Sign up to Continue': 'سجل للمتابعة',
          'Your Name': 'اسمك',
          'Enter your name': 'أدخل اسمك',
          'Shop Name': 'اسم المتجر',
          'Enter your shop name': 'أدخل اسم المتجر',
          'Phone Number': 'رقم الهاتف',
          'Enter your number': 'أدخل رقمك',
          'Continue': 'استمرار',
          'Already have an account? ': 'هل لديك حساب بالفعل؟ ',
          'Login': 'تسجيل الدخول',
          'Verification Code': 'رمز التحقق',
          'We will send verification code on your phone number':
              'سوف نرسل رمز التحقق إلى رقم هاتفك',
          'Code': 'الرمز',
          '4-Type of Number': 'رمز مكوّن من 4 أرقام',
          'Verify': 'تحقق',
          'Log in': 'تسجيل الدخول',
          'Welcome back!': 'مرحباً بعودتك!',
          'Stay signed in with your account to make easier':
              'ابقَ مسجلاً للدخول لتسهيل الوصول',
          'Mobile Number': 'رقم الجوال',
          'Enter your mobile number': 'أدخل رقم الجوال',
          'Setting': 'الإعدادات',
          'Log Out': 'تسجيل الخروج',
          'Are You Sure you Want to log out':
              'هل أنت متأكد أنك تريد تسجيل الخروج؟',
          'Cancel': 'إلغاء',
          'Yes, Log Out': 'نعم، تسجيل الخروج',
          'Search product': 'ابحث عن منتج',
          'Back': 'عودة',
          'Call an Advisor': 'اتصل بمستشار',
          'Chat on WhatsApp': 'الدردشة عبر واتساب',
          'All Categories': 'جميع الفئات',
          'Most Sales': 'الأكثر مبيعاً',
          'Our Offer': 'عرضنا',
          'All Products': 'جميع المنتجات',
          'My Cart': 'سلة المشتريات',
          'Remove': 'إزالة',
          'Subtotal:': 'الإجمالي الفرعي:',
          'Logistics cost:': 'تكلفة الشحن:',
          'Logistics discount:': 'خصم الشحن:',
          'VAT:': 'الضريبة:',
          'Total Amount:': 'المبلغ الإجمالي:',
          'Order Now': 'اطلب الآن',
          'Enter your address': 'أدخل عنوانك',
          'Add Address': 'أضف عنواناً',
          'Venice': 'البندقية',
          'Thank You!': 'شكراً لك!',
          'Your order has been successfully placed.': 'تم تقديم طلبك بنجاح.',
          'View Details': 'عرض التفاصيل',
          'Deliver to ': 'التوصيل إلى ',
          'Total Payable Amount': 'إجمالي المبلغ المستحق',
          'Explore more products': 'استكشاف المزيد من المنتجات',
          'Checkout': 'الدفع',
          'Name': 'الاسم',
          'Phone': 'الهاتف',
          'Location': 'الموقع',
          'Edit Profile': 'تعديل الملف الشخصي',
          'Save': 'حفظ',
          'Add to Cart': 'أضف إلى السلة',
          'Rate': 'تقييم',
          'Ratings & Reviews': 'التقييمات والمراجعات',
          'Product Details': 'تفاصيل المنتج',
          'Home': 'الرئيسية',
          'Category': 'فئة',
          'Order': 'الطلبات',
          'Profile': 'الملف الشخصي',
          'Tracking Order': 'تتبع الطلب',
          'Complete Order': 'إكمال الطلب',
          'Arabic': "العربية",
          'French': 'الفرنسية',
          'Notification': 'إشعار',
          'Add Cart': 'أضف سلة التسوق',
          'Product Request': 'طلب المنتج',
          'Thank You For Using Review!': 'شكرًا لاستخدامك Review!',
          'Give a Review': 'إعطاء مراجعة',
          'Review Heading': 'عنوان المراجعة',
          'Text': 'النص',
          'Detail Review': 'مراجعة مفصلة',
          'Details': 'تفاصيل',
          'Submit': 'إرسال',
          'Verify account': 'تأكيد الحساب',
          'Code has been send to ': 'تم إرسال الرمز إلى ',
          ' Enter the code to verify your account.':
              ' أدخل الرمز لتأكيد حسابك.',
          'Code': 'الرمز',
          'Verify Account': 'تأكيد الحساب',
          'Rated': 'تم تقييمه',
          'Remove from Cart': 'إزالة من السلة'
        }
      };
}
