
// import 'package:rxdart/rxdart.dart';
// import 'package:slenderblender_app/features/auth/data/rx_post_login/rx.dart';
// import 'package:slenderblender_app/features/auth/data/rx_social_login/rx.dart';
// import 'package:slenderblender_app/features/auth/model/login_model.dart';
// import 'package:slenderblender_app/features/auth/model/otp_verify_model.dart';
// import 'package:slenderblender_app/features/auth/password/data/rx_post_create_pass/rx.dart';
// import 'package:slenderblender_app/features/auth/password/data/rx_post_send_pass_otp/rx.dart';
// import 'package:slenderblender_app/features/auth/password/data/rx_post_verify_otp_pass/rx.dart';
// import 'package:slenderblender_app/features/auth/verification/data/rx_post_resend_otp/rx.dart';
// import 'package:slenderblender_app/features/auth/verification/data/rx_post_send_otp/rx.dart';
// import 'package:slenderblender_app/features/auth/verification/data/rx_post_verify_otp/rx.dart';
// import 'package:slenderblender_app/features/choose_plan/data/rx_post_onboarding_setup/rx.dart';
// import 'package:slenderblender_app/features/event/data/rx_get_my_all_event/rx.dart';
// import 'package:slenderblender_app/features/event/data/rx_get_single_event/rx.dart';
// import 'package:slenderblender_app/features/event/data/rx_post_store_event/rx.dart';
// import 'package:slenderblender_app/features/event/data/rx_patch_update_event/rx.dart';
// import 'package:slenderblender_app/features/event/model/my_event_model.dart';
// import 'package:slenderblender_app/features/event/model/single_event_model.dart';
// import 'package:slenderblender_app/features/home/data/rx__get_category/rx.dart';
// import 'package:slenderblender_app/features/home/data/rx_get_comment/rx.dart';
// import 'package:slenderblender_app/features/home/data/rx_get_post/rx.dart';
// import 'package:slenderblender_app/features/home/data/rx_post_comment/rx.dart';
// import 'package:slenderblender_app/features/home/data/rx_post_react/rx.dart';
// import 'package:slenderblender_app/features/home/data/rx_post_store_post/rx.dart';
// import 'package:slenderblender_app/features/home/model/category_model.dart';
// import 'package:slenderblender_app/features/home/model/comment_model.dart';
// import 'package:slenderblender_app/features/home/model/post_model.dart';
// import 'package:slenderblender_app/features/profile/data/rx_get_group/rx.dart';
// import 'package:slenderblender_app/features/profile/data/rx_get_message/rx.dart';
// import 'package:slenderblender_app/features/profile/data/rx_get_profile_data/rx.dart';
// import 'package:slenderblender_app/features/profile/data/rx_post_change_password/rx.dart';
// import 'package:slenderblender_app/features/profile/data/rx_post_logout/rx.dart';
// import 'package:slenderblender_app/features/profile/data/rx_post_send_message/rx.dart';
// import 'package:slenderblender_app/features/profile/data/rx_post_update_profile/rx.dart';
// import 'package:slenderblender_app/features/profile/model/chat_model.dart';
// import 'package:slenderblender_app/features/profile/model/message_list_model.dart';
// import 'package:slenderblender_app/features/profile/model/profile_data_model.dart';
// import 'package:slenderblender_app/features/titration_tracker/data/rx_delete_titration/rx.dart';
// import 'package:slenderblender_app/features/titration_tracker/data/rx_get_titration_list/rx.dart';
// import 'package:slenderblender_app/features/titration_tracker/data/rx_post_create_titration/rx.dart';
// import 'package:slenderblender_app/features/titration_tracker/model/titration_list_model.dart';
// import 'package:slenderblender_app/features/tools/data/rx_delete_medication/rx.dart';
// import 'package:slenderblender_app/features/tools/data/rx_delete_thought/rx.dart';
// import 'package:slenderblender_app/features/tools/data/rx_get_medication_tracker_list/rx.dart';
// import 'package:slenderblender_app/features/tools/data/rx_get_routine_list/rx.dart';
// import 'package:slenderblender_app/features/tools/data/rx_get_thought_list/rx.dart';
// import 'package:slenderblender_app/features/tools/data/rx_post_store_medication/rx.dart';
// import 'package:slenderblender_app/features/tools/data/rx_post_store_routine/rx.dart';
// import 'package:slenderblender_app/features/tools/data/rx_post_store_thought/rx.dart';
// import 'package:slenderblender_app/features/tools/model/medication_tracker_list_model.dart';
// import 'package:slenderblender_app/features/tools/model/routine_list_model.dart';
// import 'package:slenderblender_app/features/tools/model/thought_dump_model.dart';

// UserLoginRx userLoginRXObj = UserLoginRx(empty: LoginModel(), dataFetcher: BehaviorSubject<LoginModel>());
// LogoutRx logoutRxObj = LogoutRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// SendOtpRx sendOtpRxObj = SendOtpRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// OtpVerifyRX otpVerifyRXObj = OtpVerifyRX(empty: OtpVerifyModel(), dataFetcher: BehaviorSubject<OtpVerifyModel>());
// ResendOtpRx resendOtpRxObj = ResendOtpRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// SendOtpPassRx sendOtpPassRxObj = SendOtpPassRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// OtpVerifyPassRx otpVerifyPassRxObj = OtpVerifyPassRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// PostResetPasswordRx postResetPasswordRxObj = PostResetPasswordRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// GetOwnProfileRx getOwnProfileRxObj = GetOwnProfileRx(empty: ProfileDataModel(), dataFetcher: BehaviorSubject<ProfileDataModel>());
// UpdateProfileRX updateProfileRXObj = UpdateProfileRX(empty: {}, dataFetcher: BehaviorSubject<Map>());
// ChangePasswordRx changePasswordRxObj = ChangePasswordRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// GetSingleEventRx getSingleEventRxObj = GetSingleEventRx(empty: SingleEventModel(), dataFetcher: BehaviorSubject<SingleEventModel>());
// PostStoreEventRx postStoreEventRxObj = PostStoreEventRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// GetMyEventRx getMyEventRxObj = GetMyEventRx(empty: MyEventModel(), dataFetcher: BehaviorSubject<MyEventModel>());
// UpdateEventRx updateEventRxObj = UpdateEventRx(empty: {}, dataFetcher: BehaviorSubject<Map>()); 
// PostStoreRoutineRx postStoreRoutineRxObj = PostStoreRoutineRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// GetRoutineListRx getRoutineListRxObj = GetRoutineListRx(empty: RoutineListModel(), dataFetcher: BehaviorSubject<RoutineListModel>());
// PostStoreMedicationRx postStoreMedicationRxObj = PostStoreMedicationRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// GetMedicationListRx getMedicationListRxObj = GetMedicationListRx(empty: MedicationTrackerListModel(), dataFetcher: BehaviorSubject<MedicationTrackerListModel>());
// PostStoreThoughtRx postStoreThoughtRxObj = PostStoreThoughtRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// GetThoughtListRx getThoughtListRxObj = GetThoughtListRx(empty: ThoughtDumpModel(), dataFetcher: BehaviorSubject<ThoughtDumpModel>());
// GetPostRx getPostRxObj = GetPostRx(empty: PostModel(), dataFetcher: BehaviorSubject<PostModel>());
// SocialLoginRX socialLoginRXObj = SocialLoginRX(empty: LoginModel(), dataFetcher: BehaviorSubject<LoginModel>());
// GetCategoryRx getCategoryRxObj = GetCategoryRx(empty: CategoryModel(), dataFetcher: BehaviorSubject<CategoryModel>());
// StorePostRX storePostRXObj = StorePostRX(empty: {}, dataFetcher: BehaviorSubject<Map>());
// PostStoreReactRx postStoreReactRxObj = PostStoreReactRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// PostOnboardingSetupRx postOnboardingSetupRxObj = PostOnboardingSetupRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// GetCommentRx getCommentRxObj = GetCommentRx(empty: CommentModel(), dataFetcher: BehaviorSubject<CommentModel>());
// StoreCommentRX storeCommentRXObj = StoreCommentRX(empty: {}, dataFetcher: BehaviorSubject<Map>());
// GetMessageListRx getMessageListRxObj = GetMessageListRx(empty: MessageListModel(), dataFetcher: BehaviorSubject<MessageListModel>());
// GetChatListRx getChatListRxObj = GetChatListRx(empty: ChatModel(), dataFetcher: BehaviorSubject<ChatModel>());
// PostMessageSendRx postMessageSendRxObj = PostMessageSendRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// GetTitrationListRx getTitrationListRxObj = GetTitrationListRx(empty: TitrationListModel(), dataFetcher: BehaviorSubject<TitrationListModel>());
// PostStoreTitrationRx postStoreTitrationRxObj = PostStoreTitrationRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// DeleteTitrationRx deleteTitrationRxObj = DeleteTitrationRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// DeleteThoughtRx deleteThoughtRxObj = DeleteThoughtRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
// DeleteMedicationRx deleteMedicationRxObj = DeleteMedicationRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
